name: Publish docker image

on:
  push:
    branches:
      - master         # Push events on master branch

jobs:
  deploy-judi-image:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ['1.6', '1.7']

    steps:
      - name: Checkout JUDI4Cloud
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.1.2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: JUDI4Cloud image
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: ./docker/Dockerfile.runtime
          push: true
          network: host
          build-args: JVER=${{ matrix.version }}
          tags: mloubout/judi4cloud:${{ matrix.version }}
